name: file_manager
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  flutter_riverpod: ^2.3.6
  external_path: ^1.0.3
  path: ^1.8.2
  awesome_icons: ^1.1.0
  intl: ^0.18.1
  open_app_file: ^4.0.1
  fluttertoast: ^8.2.1
  jaguar: ^3.1.3
  local_assets_server: ^2.0.2+12
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true